### PR TITLE
Change default FELIX_LOGSEVERITYSCREEN from info to error

### PR DESCRIPTION
**Pull request by nutellinoit**
Hi guys, minor change on networking side.

Calico is logging A LOT non useful stuff, causing pressure on the logging side.

I changed FELIX_LOGSEVERITYSCREEN from info to error

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Not sure if we should ship it by default seted to error or info. I will hold the review until listening more point of views.

**Comment by nutellinoit** [comment]
Before and after

Screenshot 2020-05-25 at 10 57 39

**Comment by lzecca78** [comment]
i am  fully agree with @nutellinoit . I would also like to make a similar discussion for audit logging that is pretty much intensive and should be refined in order to keep only "interesting events" and not "everything" because at the end, only the "errors" are useful when you analyze a post-mortem or issue context.

**Comment by angelbarrera92** [comment]
Exactly, is not only how many logs are the CNI emitting, there are other components emitting a huge amount of logs with the "default" configuration. So... three options:

1. Ship with the default logging configuration as we are currently doing. Then, as part of the delivery team work, you should ask client if they want info or error log level.
2. Change the default log level we are shipping, not only in the CNI but in all components. Then as part of the delivery team work, ask the client if they want more verbosity.
3. Change just the calico log level because it was bad implemented by calico project team (in this case) (they should emit current info logs -> debug).

What's your opinion?

**Comment by lnovara** [comment]
I would go with 3 and than evaluate the other components in case they are logging too much without providing any useful information.

**Comment by phisco** [comment]
I agree about lowering the calico logging level.

Regarding the audit log, it is an audit log, so it should be complete, but as @angelbarrera92 was saying it should be a requirement from the customer whether auditability is needed or not in their specific context, for debugging purposes storing just errors should be more than enough.
I think we should definitely discuss this in a separate PR/Issue.

**Comment by angelbarrera92** [comment]
I will add an "unreleased" markdown file under docs/releases to don't forget to include it in the next release

**Pull request merged**
